aluno/urls.py
from django.urls import path
from . import views

app_name = 'aluno'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('cadastrar/', views.cadastrar_aluno, name='cadastrar'),
    path('editar/<int:id>', views.editar_aluno, name='editar'),
    path('deletar/<int:id>', views.deletar_aluno, name='deletar'),
]

curso/urls.py
from django.urls import path

from . import views

app_name = 'curso'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar')
]

main/urls.py
from django.urls import path
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    #path('login/', IndexView.as_view(), name='login'),
]

professor/urls.py
from django.urls import path

from . import views

app_name = 'professor'

urlpatterns = [

    path('', views.dashboard, name='dashboard'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar')
    
]

sysif/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('aluno/', include('aluno.urls')),
    path('turma/', include('turma.urls')),
    path('professor/', include('professor.urls')),
    path('disciplina/', include('disciplina.urls')),
    path('curso/', include('curso.urls')),
    path('', include('usuarios.urls')),
]

turma/urls.py
from django.urls import path
from . import views

app_name = 'turma'

urlpatterns = [
    path('', views.dashboard_turma, name='dashboard'),
    path('cadastrar/', views.cadastrar_turma, name='cadastrar'),
    path('editar/<int:id>', views.editar_turma, name='editar'),
    path('deletar/<int:id>', views.deletar_turma, name='deletar'),
    path('avaliacao/', views.dashboard_avaliacao, name='dashboardAvaliacao'),
    path('lancarAvaliacao/', views.lancar_avaliacao, name='lancarAvaliacao'),
    path('editarAvaliacao/<int:id>', views.editar_avaliacao, name='editarAvaliacao'),
    path('deletarAvaliacao/<int:id>', views.deletar_avaliacao, name='deletarAvaliacao'),
    path('alocarAluno/', views.alocar_aluno, name = 'alocarAluno'),
    path('verAlunos/<int:id>', views.ver_alunos, name='verAlunos'),
    path('retirarAlunos/<int:id>, <int:idt>', views.retirar_alunos, name ='retirarAlunos'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.

class HomeView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('login')
    template_name = "home.html"

main/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" type="image/x-icon" href="../../static/img/logo_home.png">

  <!-- Durval - Framework Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Durval - Carregando Javascript do Bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>

  <!-- Durval - Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">

  <!-- Durval - Folha de estilo -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>SysIF</title>
</head>

<body>
  <!-- Durval - carrega cabeçalho da pasta partials -->

  {% include 'partials/navbar.html' %}
 
  <section class="caixa">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-12 d-flex crud-container ">
          <div class="crud-section col-12">
            <div class="regulador">
              {% block content %}

              {% endblock %}
            </div>
          </div>
        </div>
      </div>
  </section><!--/FIM seção saiba -->

</body>

</html>

main/templates/home.html
{% extends 'base.html' %} 

{% load static %}

{% block title %}Home{% endblock %}

{% block content %} 


<div class="form-title box justify-content-center">
    <h3>PAINEL DE CONTROLE</h3>
 </div>

<div class="row justify-content-center">
     <a href="{% url 'aluno:dashboard'%}" class="col-4 d-inline-block dash-item "> <img src="../../static/img/aluno_dashboard2.png" alt="" width="60px"> <span>Aluno</span> </a> 
    <a href="{% url 'professor:dashboard'%}" class="col-4 d-inline-block dash-item"> <img src="../../static/img/prof_dashboard2.png" alt="" width="60px"> <span>Professor</span></a> 
     <a href="{% url 'curso:dashboard'%}" class="col-4 d-inline-block dash-item"> <img src="../../static/img/curso_dashboard2.png" alt="" width="60px"> <span>Cursos</span></a> 
    </div>
        
     
<div class="row justify-content-center">
     <a href="{% url 'disciplina:dashboard'%}" class="col-4 d-inline-block dash-item"> <img src="../../static/img/disci_dashboard2.png" alt="" width="60px"> <span>Disciplina</span> </a>
    <a  href="{% url 'turma:dashboard'%}" class="col-4 d-inline-block dash-item"> <img src="../../static/img/turma_dashboard2.png" alt="" width="60px"> <span> Turma </span> </a> 
    <a  href="{% url 'turma:dashboardAvaliacao'%}" class="col-4 d-inline-block dash-item"> <img src="../../static/img/avali_dashboard2.png" alt="" width="60px"> <span>  Avaliação</span></a>
</div>

{% endblock %}